/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.ActionListener;

/**
 *
 * @author Elang
 */
public class AboutPanel extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public AboutPanel() {
        initComponents();
        initComponentUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tentangButton = new javax.swing.JButton();
        olehButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        tentangButton.setText("Tentang");

        olehButton.setText("Oleh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tentangButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(olehButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tentangButton)
                    .addComponent(olehButton))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
        
        private void initComponentUser(){
        tentangButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
             jTextArea1.setText(">Congklak<\n\nCongklak adalah permainan tradisional yang berasal dari \nIndonesia, Malaysia, Singapur dan beberapa negara Asia \nTenggara lainnya.. Nama Congklak berasal dari bahasa \nmelayu 'congkak', yang berarti 'menghitung dalam otak'\n\n>Aturan Main<\nCongklak dimainkan oleh dua orang. Salah satu pemain\nmemulai permainan dengan mengambil biji dari lubang \nsisi pemain tersebut. Biji lalu dijalankan dengan \ndijatuhkan ke setiap lubang yang ia lewati, kecuali \nlubang skor lawan. \n\nJika biji terakhir dijatuhkan di lubang skor, maka \npemain kembali mengambil biji dari lubang sisinya \ndan menjalankannya.\n\nJika biji terakhir dijatuhkan di lubang biasa yang tidak\nkosong(termasuk lubang di sisi lawan) , maka pemain \nmengambil semua biji di lubang tersebut dan \nmelanjutkan perjalanan dari lubang tersebut.\n\nJika biji terakhir terjatuh di lubang kosong sisi pemain, \nmaka biji tersebut beserta semua biji di lubang lawan \nyang bersebrangan dimasukkan ke lubang skor pemain. \nGiliran pemain selesai\n\nJika biji terakhir jatuh di lubang kosong sisi lawan, \nmaka giliran pemain berhenti\n\nGame berakhir ketika sudah tidak ada biji di \nlubang kedua pemain\n\nPemenang adalah mereka yang memiliki biji terbanyak\ndi kotak skornya");
            }
        });
        
            olehButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextArea1.setText("Oleh : Kelompok 4 MPKT-A Kelas D, FASILKOM UI\n\nAnggota :\nAgus Sentosa (Back-End)\nFersandi Pratama (Front-End)\nAhmad Elang\nMuhhamad Umar Farisi\nFadzil Rizki\nIrena");
            }
        });
    }


    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton olehButton;
    private javax.swing.JButton tentangButton;
    // End of variables declaration                   
}
